### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'action_space'

### ISSUE THREAD

**Issue by JKK-dr** [rllab-snu/TopologicalSemanticGraphMemory#15]
Traceback (most recent call last):
  File "train_il.py", line 269, in <module>
    train()
  File "train_il.py", line 109, in train
    trainer = eval(config.TASK_CONFIG.IL_TRAINER)(config, policy)
  File "/data/polaris/TopologicalSemanticGraphMemory-master/trainer/il/il_trainer.py", line 15, in __init__
    self.env_wrapper = eval(cfg.IL.WRAPPER)(None)
  File "/data/polaris/TopologicalSemanticGraphMemory-master/trainer/il/il_wrapper.py", line 11, in __init__
    super().__init__(env)
  File "/data/Tool/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/core.py", line 227, in __init__
    self.action_space = self.env.action_space
AttributeError: 'NoneType' object has no attribute 'action_space'
I meet this problem. Can you help me?

**Comment by calcualatexzy** [comment]
exactly same problem here! Have you managed to solve it?

**Comment by bareblackfoot** [comment]
Hello, Thanks for your interest in our work :).
I think gym version is mismatched. please downgrade the gym version.
Thanks

**Comment by McGrady-175** [comment]
> Hello, Thanks for your interest in our work :). I think gym version is mismatched. please downgrade the gym version. Thanks

hi, my gym~=0.20.0, why is it still reporting an error?
