### ISSUE TITLE
assert cls.check_config_paths_exist(config)

### ISSUE THREAD

**Issue by qinhaijian23** [rllab-snu/TopologicalSemanticGraphMemory#17]
File "/home/name/habitat-lab/habitat_baselines/rl/ppo/ppo_trainer.py", line 288, in train
self.config, get_env_class(self.config.ENV_NAME)
File "/home/name/habitat-lab/habitat_baselines/utils/env_utils.py", line 43, in construct_envs
scenes = dataset.get_scenes_to_load(config.TASK_CONFIG.DATASET)
File "/home/name/habitat-lab/habitat/datasets/pointnav/pointnav_dataset.py", line 43, in get_scenes_to_load
assert cls.check_config_paths_exist(config)
AssertionError

"You can follow the instructions here: https://github.com/facebookresearch/habitat-lab#data"
Sorry to bother you. I entered this link through the method you mentioned to learn, but I still haven't found a solution. Can you provide me with a more detailed introduction? I don't quite understand how to choose the path when configuring the environment. Looking forward to your reply, thank you very much. Sorry again for bothering you.

**Comment by letthink** [comment]
Hi,maybe you need choose the data about Point goal navigation.
First go to task datasets to download this data:[https://github.com/facebookresearch/habitat-lab/blob/main/DATASETS.md](url). 
Second choose the task "Point goal navigation	Gibson	pointnav_gibson_v1.zip	data/datasets/pointnav/gibson/v1/	datasets/pointnav/gibson.yaml	385 MB"in [https://github.com/facebookresearch/habitat-lab/blob/main/DATASETS.md#task-datasets](url). 
Third, unzip this dataset in the true data path,refer to "TopologicalSemanticGraphMemory/programs/habitat-lab-v21/data/datasets/pointnav".
Have a good day!

**Comment by qinhaijian23** [comment]
> Hi,maybe you need choose the data about Point goal navigation. First go to task datasets to download this data:[https://github.com/facebookresearch/habitat-lab/blob/main/DATASETS.md](url). Second choose the task "Point goal navigation Gibson pointnav_gibson_v1.zip data/datasets/pointnav/gibson/v1/ datasets/pointnav/gibson.yaml 385 MB"in [https://github.com/facebookresearch/habitat-lab/blob/main/DATASETS.md#task-datasets](url). Third, unzip this dataset in the true data path,refer to "TopologicalSemanticGraphMemory/programs/habitat-lab-v21/data/datasets/pointnav". Have a good day!

hello,thank you very much for your reply. I will make corrections according to your method, but now I have faced a new problem. Do you have time to help answer it? This is my first time using Ubuntu to configure the environment, and there are still many things I don't understand that I need to consult with you all.  Q:collected splits.tar.gz 1
Traceback (most recent call last):
  File "collect_il_data.py", line 290, in <module>
    main()
  File "collect_il_data.py", line 260, in main
    if len(list_collected) < ep_per_env[cs]:
KeyError: 'splits.tar.gz'
I am deeply indebted to you for your help.

**Comment by letthink** [comment]
Well,I don't use the collect_il_data.py to generate this data now. I get the data from google cloud drive [https://drive.google.com/drive/folders/1-8srO6kwxf_qxnIWdH6K7AToP_oxWEYg](url). You can get more information from README, best wish.

**Comment by qinhaijian23** [comment]
> Well,I don't use the collect_il_data.py to generate this data now. I get the data from google cloud drive [https://drive.google.com/drive/folders/1-8srO6kwxf_qxnIWdH6K7AToP_oxWEYg](url). You can get more information from README, best wish.

Thank you again, I followed your advice to get the data from Google cloud, but when I run the code according to the README：“python train_il.py --policy TSGMPolicy --config configs/TSGM.yaml --version exp_name --data-dir IL_data/gibson --prebuild-path IL_data/gibson_graph”, https://github.com/rllab-snu/TopologicalSemanticGraphMemory/tree/master. I still have some problems, how do you check all your paths? I feel a bit confused, for the path piece, can you teach me how you set up your paths?I'm very sorry for taking up your time, and thank you very much for taking the time to reply!    Q：python train_il.py --policy TSGMPolicy --config configs/TSGM.yaml --version exp_name --data-dir IL_data/gibson --prebuild-path IL_data/gibson_graph
/home/cn/anaconda3/envs/tsgm/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator GaussianMixture from version 0.22.2.post1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
====================================
Dataset Name:  gibson
POLICY : TSGMPolicy
Image Graph Threshold:  0.75
Object Graph Threshold:  0.8
====================================
Traceback (most recent call last):
  File "train_il.py", line 269, in <module>
    train()
  File "train_il.py", line 138, in train
    valid_dataloader = DataLoader(valid_dataset, **valid_params)
  File "/home/cn/anaconda3/envs/tsgm/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/home/cn/anaconda3/envs/tsgm/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 103, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
