### ISSUE TITLE
Error when run collect_il_data.py

### ISSUE THREAD

**Issue by leyuan-sun** [rllab-snu/TopologicalSemanticGraphMemory#4]
I have fixed a lot bugs but still cannot run your project, could you please take a loot? Thanks!!!
=================================================
SPACE[001/071] STARTED Albertville
/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator GaussianMixture from version 0.22.2.post1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator GaussianMixture from version 0.22.2.post1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
[ImageGoalEnv] NOISY ACTUATION :  False
[ImageGoalEnv] NOISY ACTUATION :  False
[HabitatEnv][Proc 0] Total 1 scenes:  ['Albertville']
[HabitatEnv][Proc 2] Total 1 scenes:  ['Albertville']
[HabitatEnv][Proc 0] swap building every  2000
[HabitatEnv][Proc 2] swap building every  2000
2023-05-26 22:12:23,351 initializing sim Sim-0
2023-05-26 22:12:23,351 initializing sim Sim-0
/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator GaussianMixture from version 0.22.2.post1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator GaussianMixture from version 0.22.2.post1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
[ImageGoalEnv] NOISY ACTUATION :  False
[ImageGoalEnv] NOISY ACTUATION :  False
[HabitatEnv][Proc 3] Total 1 scenes:  ['Albertville']
[HabitatEnv][Proc 1] Total 1 scenes:  ['Albertville']
[HabitatEnv][Proc 3] swap building every  2000
[HabitatEnv][Proc 1] swap building every  2000
2023-05-26 22:12:23,365 initializing sim Sim-0
2023-05-26 22:12:23,365 initializing sim Sim-0
2023-05-26 22:12:25,841 Initializing task Nav-v0
2023-05-26 22:12:26,076 Initializing task Nav-v0
2023-05-26 22:12:26,093 Initializing task Nav-v0
2023-05-26 22:12:26,103 Initializing task Nav-v0
Process ForkServerProcess-3:
Traceback (most recent call last):
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 233, in _worker_env
    env = env_fn(*env_fn_args)
  File "/home/sly/TopologicalSemanticGraphMemory/collect_il_data.py", line 47, in make_env_fn
    env = eval(config_env.ENV_NAME)(config=config_env)
  File "/home/sly/TopologicalSemanticGraphMemory/env_utils/imagegoal_env.py", line 890, in __init__
    super(MultiImageGoalEnv, self).__init__(config)
  File "/home/sly/TopologicalSemanticGraphMemory/env_utils/imagegoal_env.py", line 128, in __init__
    obs_dict['object_mask'] = Box(low=-np.Inf, high=np.Inf, shape=(self.config.memory.num_objects,), dtype=np.bool)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 109, in __init__
    low = _broadcast(low, dtype, shape, inf_sign="-")  # type: ignore
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 329, in _broadcast
    value = get_inf(dtype, inf_sign) if np.isinf(value) else value  # type: ignore
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 310, in get_inf
    **raise ValueError(f"Unknown dtype {dtype} for infinite bounds")
ValueError: Unknown dtype <class 'bool'> for infinite bounds**
Process ForkServerProcess-4:
Traceback (most recent call last):
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 233, in _worker_env
    env = env_fn(*env_fn_args)
  File "/home/sly/TopologicalSemanticGraphMemory/collect_il_data.py", line 47, in make_env_fn
    env = eval(config_env.ENV_NAME)(config=config_env)
  File "/home/sly/TopologicalSemanticGraphMemory/env_utils/imagegoal_env.py", line 890, in __init__
    super(MultiImageGoalEnv, self).__init__(config)
  File "/home/sly/TopologicalSemanticGraphMemory/env_utils/imagegoal_env.py", line 128, in __init__
    obs_dict['object_mask'] = Box(low=-np.Inf, high=np.Inf, shape=(self.config.memory.num_objects,), dtype=np.bool)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 109, in __init__
    low = _broadcast(low, dtype, shape, inf_sign="-")  # type: ignore
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 329, in _broadcast
    value = get_inf(dtype, inf_sign) if np.isinf(value) else value  # type: ignore
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 310, in get_inf
    raise ValueError(f"Unknown dtype {dtype} for infinite bounds")
ValueError: Unknown dtype <class 'bool'> for infinite bounds
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 233, in _worker_env
    env = env_fn(*env_fn_args)
  File "/home/sly/TopologicalSemanticGraphMemory/collect_il_data.py", line 47, in make_env_fn
    env = eval(config_env.ENV_NAME)(config=config_env)
  File "/home/sly/TopologicalSemanticGraphMemory/env_utils/imagegoal_env.py", line 890, in __init__
    super(MultiImageGoalEnv, self).__init__(config)
  File "/home/sly/TopologicalSemanticGraphMemory/env_utils/imagegoal_env.py", line 128, in __init__
    obs_dict['object_mask'] = Box(low=-np.Inf, high=np.Inf, shape=(self.config.memory.num_objects,), dtype=np.bool)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 109, in __init__
    low = _broadcast(low, dtype, shape, inf_sign="-")  # type: ignore
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 329, in _broadcast
    value = get_inf(dtype, inf_sign) if np.isinf(value) else value  # type: ignore
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 310, in get_inf
    raise ValueError(f"Unknown dtype {dtype} for infinite bounds")
ValueError: Unknown dtype <class 'bool'> for infinite bounds
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 233, in _worker_env
    env = env_fn(*env_fn_args)
  File "/home/sly/TopologicalSemanticGraphMemory/collect_il_data.py", line 47, in make_env_fn
    env = eval(config_env.ENV_NAME)(config=config_env)
  File "/home/sly/TopologicalSemanticGraphMemory/env_utils/imagegoal_env.py", line 890, in __init__
    super(MultiImageGoalEnv, self).__init__(config)
  File "/home/sly/TopologicalSemanticGraphMemory/env_utils/imagegoal_env.py", line 128, in __init__
    obs_dict['object_mask'] = Box(low=-np.Inf, high=np.Inf, shape=(self.config.memory.num_objects,), dtype=np.bool)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 109, in __init__
    low = _broadcast(low, dtype, shape, inf_sign="-")  # type: ignore
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 329, in _broadcast
    value = get_inf(dtype, inf_sign) if np.isinf(value) else value  # type: ignore
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/site-packages/gym/spaces/box.py", line 310, in get_inf
    raise ValueError(f"Unknown dtype {dtype} for infinite bounds")
ValueError: Unknown dtype <class 'bool'> for infinite bounds
Traceback (most recent call last):
  File "collect_il_data.py", line 288, in <module>
    main()
  File "collect_il_data.py", line 284, in main
    data_collect(config, DATA_DIR, space_id, len(scenes), start_idx, ep_per_env[space])
  File "collect_il_data.py", line 74, in data_collect
    auto_reset_done=False
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 194, in __init__
    read_fn() for read_fn in self._connection_read_fns
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 194, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <function VectorEnv.__del__ at 0x7f4fb5be5f80>
Traceback (most recent call last):
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 592, in __del__
    self.close()
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 460, in close
    read_fn()
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/home/sly/TopologicalSemanticGraphMemory/programs/habitat-lab-v21/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/sly/anaconda3/envs/tsgm/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError:

**Comment by bareblackfoot** [comment]
I believe the error is caused by a version discrepancy in the 'gym' package. Please change the 'gym' version to 0.21.0.

**Comment by bareblackfoot** [comment]
I updated files and codes to fix errors :)
Please check it out 😉
